
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Karyawan extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        load_table();
    }

    UbahDataKaryawan jtRowData = new UbahDataKaryawan();
    
    private void load_table(){
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Karyawan");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("No Telepon");

        //menampilkan data database kedalam tabel
        try {
            String sql = "select * from karyawan where not `kd_karyawan` = 'K666' AND NOT  `kd_karyawan` = 'K555' order by `kd_karyawan` asc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2), res.getString(3), res.getString(4),
                    res.getString(5)});
            }
            jTablekaryawan.setModel(model);
        } catch (Exception e){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        lbl_produk = new javax.swing.JLabel();
        lbl_penjualan = new javax.swing.JLabel();
        lbl_pembelian = new javax.swing.JLabel();
        lbl_karyawan = new javax.swing.JLabel();
        lbl_laporan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablekaryawan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(1380, 100));

        lbl_logout.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setText("LOGOUT");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1275, Short.MAX_VALUE)
                .addComponent(lbl_logout)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lbl_logout)
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(170, 630));

        lbl_dashboard.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(0, 153, 153));
        lbl_dashboard.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\dashboard2.PNG")); // NOI18N
        lbl_dashboard.setText("DASHBOARD");
        lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseClicked(evt);
            }
        });

        lbl_produk.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_produk.setForeground(new java.awt.Color(0, 153, 153));
        lbl_produk.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\produk2.png")); // NOI18N
        lbl_produk.setText("PRODUK");
        lbl_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_produkMouseClicked(evt);
            }
        });

        lbl_penjualan.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_penjualan.setForeground(new java.awt.Color(0, 153, 153));
        lbl_penjualan.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\penjualan2.png")); // NOI18N
        lbl_penjualan.setText("PENJUALAN");
        lbl_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_penjualanMouseClicked(evt);
            }
        });

        lbl_pembelian.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_pembelian.setForeground(new java.awt.Color(0, 153, 153));
        lbl_pembelian.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\pembelian2.png")); // NOI18N
        lbl_pembelian.setText("PEMBELIAN");
        lbl_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pembelianMouseClicked(evt);
            }
        });

        lbl_karyawan.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_karyawan.setForeground(new java.awt.Color(102, 102, 102));
        lbl_karyawan.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\karyawan.png")); // NOI18N
        lbl_karyawan.setText("KARYAWAN");

        lbl_laporan.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lbl_laporan.setForeground(new java.awt.Color(0, 153, 153));
        lbl_laporan.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\laporan2.png")); // NOI18N
        lbl_laporan.setText("LAPORAN");
        lbl_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_laporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_laporan)
                    .addComponent(lbl_karyawan)
                    .addComponent(lbl_pembelian)
                    .addComponent(lbl_penjualan)
                    .addComponent(lbl_produk)
                    .addComponent(lbl_dashboard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbl_dashboard)
                .addGap(45, 45, 45)
                .addComponent(lbl_produk)
                .addGap(45, 45, 45)
                .addComponent(lbl_penjualan)
                .addGap(45, 45, 45)
                .addComponent(lbl_pembelian)
                .addGap(45, 45, 45)
                .addComponent(lbl_karyawan)
                .addGap(45, 45, 45)
                .addComponent(lbl_laporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, -1, 620));

        jTablekaryawan.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jTablekaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablekaryawan.setRowHeight(30);
        jTablekaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablekaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablekaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 1170, 470));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 50));

        btn_tambah.setBackground(new java.awt.Color(0, 102, 102));
        btn_tambah.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH DATA");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(255, 0, 51));
        btn_hapus.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setBackground(new java.awt.Color(0, 153, 255));
        btn_ubah.setFont(new java.awt.Font("Yu Gothic UI", 1, 13)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("UBAH");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_tambah)
                .addGap(81, 81, 81)
                .addComponent(btn_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btn_ubah)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_hapus)
                    .addComponent(btn_ubah))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Project5A\\Project Akhir semester 1\\ICON\\4.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 730));

        setSize(new java.awt.Dimension(1398, 777));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_lbl_dashboardMouseClicked

    private void lbl_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_produkMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Produk().setVisible(true);
    }//GEN-LAST:event_lbl_produkMouseClicked

    private void lbl_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_penjualanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Penjualan().setVisible(true);
    }//GEN-LAST:event_lbl_penjualanMouseClicked

    private void lbl_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pembelianMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Pembelian().setVisible(true);
    }//GEN-LAST:event_lbl_pembelianMouseClicked

    private void lbl_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_laporanMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Laporan().setVisible(true);
    }//GEN-LAST:event_lbl_laporanMouseClicked

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new TambahDataKaryawan().setVisible(true);

    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        int index = jTablekaryawan.getSelectedRow();
        TableModel model = jTablekaryawan.getModel();
        String kd_karyawan = model.getValueAt(index, 0).toString();
        String nama = model.getValueAt(index, 1).toString();
        String jenis_kelamin = model.getValueAt(index, 2).toString();
        String alamat = model.getValueAt(index, 3).toString();
        String no_tlp = model.getValueAt(index, 4).toString();
        
        this.setVisible(false);
        jtRowData.setVisible(true);
        jtRowData.pack();
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        jtRowData.txt_kdKaryawan.setText(kd_karyawan);
        jtRowData.txt_kdKaryawan.disable();
        jtRowData.txt_nama.setText(nama);
        jtRowData.txt_jk.setText(jenis_kelamin);
        jtRowData.txt_alamat.setText(alamat);
        jtRowData.txt_noTlp.setText(no_tlp);
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void jTablekaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablekaryawanMouseClicked
        // TODO add your handling code here:
        int index = jTablekaryawan.getSelectedRow();
        TableModel model = jTablekaryawan.getModel();
        String kd_karyawan = model.getValueAt(index, 0).toString();
        String kd_nama= model.getValueAt(index, 1).toString();
        String jenis_kelamin = model.getValueAt(index, 2).toString();
        String alamat = model.getValueAt(index, 3).toString();
        String no_tlp = model.getValueAt(index, 4).toString();
    }//GEN-LAST:event_jTablekaryawanMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            int index = jTablekaryawan.getSelectedRow();
            TableModel model = jTablekaryawan.getModel();
            String kd_karyawan = model.getValueAt(index, 0).toString();
            String sql = "DELETE FROM karyawan WHERE kd_karyawan ='"+kd_karyawan+"'";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_hapus;
    public javax.swing.JButton btn_tambah;
    public javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablekaryawan;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_karyawan;
    private javax.swing.JLabel lbl_laporan;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_pembelian;
    private javax.swing.JLabel lbl_penjualan;
    private javax.swing.JLabel lbl_produk;
    // End of variables declaration//GEN-END:variables
}
